### ISSUE TITLE
Cannot remove module without breaking the terraform state

### ISSUE THREAD

**Issue by melvey** [92green/newrelic-lambda-layer#1]
This module adds the `anschoewe/curl` provider _and_ uses it to create the resource `.data.curl.getLayers` in https://github.com/92green/newrelic-lambda-layer/blob/main/main.tf
This means that if you remove the resource, it tries to remove the getLayers resource but no longer has the provider to do so resulting in the following error
```
Error: Provider configuration not present

To work with
module.bfu_data_lambda_v2.module.bfu_data_eventbus.module.newrelic_lambda_layer.data.curl.getLayers
(orphan) its original provider configuration at
provider["registry.terraform.io/anschoewe/curl"] is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy
module.bfu_data_lambda_v2.module.bfu_data_eventbus.module.newrelic_lambda_layer.data.curl.getLayers
(orphan), after which you can remove the provider configuration again.
```

A better solution would be to split this into two modules - one with the provider and another with the resource in order that the resources can be removed prior to removing the provider.

**Comment by davidlramirez95** [comment]
Plucking out provider from the main.tf file would not work as it needs the provider block in place in order for the resource block to work.

Refer to the [troubleshooting guide](https://github.com/92green/newrelic-lambda-layer?tab=readme-ov-file#troubleshooting) in order on how to avoid the issue of Provider configuration not present when removing module
